---
title: "spiegerl-scraper"
author: "Sofia Lai"
date: "12/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
pacman::p_load(polite, 
               rvest,
               tidyverse,
               utils,
               haven, 
               lubridate)
```

Polite scraping 
```{r}
bow("https://www.spiegel.de/",
  user_agent = "Sofia Lai - https://github.com/sofialai",
  delay = 5, force = FALSE, verbose = FALSE)
```
Scraping
```{r}
base_link_spiegel <- "https://www.spiegel.de/nachrichtenarchiv/artikel-" 

dates_spiegel <- seq(dmy('01-06-2021'), dmy('12-12-2021'), by = 'days')
dates_spiegel <- format(as.Date(dates_spiegel, '%Y-%m-%d'), "%d.%m.%Y")

links_spiegel <- paste0(base_link_spiegel, dates_spiegel, ".html")

scraper_spiegel <- function(x) {
  read_html(x) %>% 
  rvest::html_nodes('body') %>%
  xml2::xml_find_all("//span[contains(@class, 'block font-sansUI font-bold text-base')]") %>%
  html_text() 
}

headlines_spiegel <- map(links_spiegel, scraper_spiegel) %>% 
  unlist() %>% 
  as.data.frame()

write.table(headlines_spiegel, "./spiegel_headlines.csv", row.names = FALSE)
```




https://www.spiegel.de/nachrichtenarchiv/artikel-11.12.2021.html
