---
title: "dominion-post-scraper"
author: "Sofia La"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
pacman::p_load(polite, 
               rvest,
               tidyverse,
               utils, 
               haven)
```

Polite scraping 
```{r}
bow("https://www.stuff.co.nz/dominion-post",
  user_agent = "Sofia Lai - https://github.com/sofialai",
  delay = 5, force = FALSE, verbose = FALSE)
```

Scraper 
```{r}
parsed_dominion_post <- read_html("https://www.stuff.co.nz/dominion-post") 

headlines_dominion_post <- parsed_dominion_post%>% 
  rvest::html_nodes('body') %>%
  xml2::xml_find_all("//a[contains(@data-article-link-country, 'nz')]") %>%
  html_text %>% 
  unique() %>% 
  tolower() %>% 
  as.data.frame()

write.table(headlines_dominion_post, "./dominion_post_headlines.csv", append = TRUE, row.names = FALSE)

dat_dominion_post <- read_csv("./dominion_post_headlines.csv") %>% 
  unique()

write.table(dat_dominion_post, "./dominion_post_headlines.csv", row.names = FALSE)
```
