---
title: "guardian-scraper"
author: "Sofia La"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
pacman::p_load(polite, 
               rvest,
               tidyverse,
               utils,
               haven)
```

Polite scraping 
```{r}
bow("https://www.theguardian.com/international",
  user_agent = "Sofia Lai - https://github.com/sofialai",
  delay = 5, force = FALSE, verbose = FALSE)
```


Scraper 

```{r}


parsed_guardian <-
  read_html("https://www.theguardian.com/international")


headlines_guardian <- html_nodes(parsed_guardian,
                             xpath = '//*[contains(concat( " ", @class, " " ), concat( " ", "js-headline-text", " " ))]') %>% 
  html_text() %>% 
  unique() %>% 
  tolower() %>% 
  as.data.frame()



write.table(headlines_guardian, "./guardian_headlines.csv", append = TRUE, row.names = FALSE)

dat_guardian <- read_csv("./guardian_headlines.csv") %>% 
  unique() 

write.table(dat_guardian, "./guardian_headlines.csv", row.names = FALSE)


```


