---
title: "Irish Times Scraper"
author: "Sofia La"
date: "11/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
pacman::p_load(polite, 
               rvest,
               tidyverse,
               utils,
               haven)
```

Polite scraping 
```{r}
bow("https://www.irishtimes.com/",
  user_agent = "Sofia Lai - https://github.com/sofialai",
  delay = 5, force = FALSE, verbose = FALSE)
```

Scraper 

```{r}
parsed_irish_times <-
  read_html("https://www.irishtimes.com/")


headlines_irish_times <- html_nodes(parsed_irish_times,
                             xpath = '//*[contains(concat( " ", @class, " " ), concat( " ", "btn-subscribe", " " ))] | //*[contains(concat( " ", @class, " " ), concat( " ", "h4", " " ))] | //*[contains(concat( " ", @class, " " ), concat( " ", "h2", " " ))]') %>% 
  html_text %>% 
  unique() %>% 
  tolower() %>% 
  as.data.frame() %>%
  rename(headline = ".") %>% 
  mutate(headline = gsub("\\ \t\t", "", headline))


write.table(headlines_irish_times, "./irish_times_headlines.csv", append = TRUE, row.names = FALSE)

dat_irish_times <- read_csv("./irish_times_headlines.csv") %>% 
  unique()  

write.table(dat_irish_times, "./irish_times_headlines.csv", row.names = FALSE)


```
