---
title: "nz-herald-scraper"
author: "Sofia La"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
pacman::p_load(polite, 
               rvest,
               tidyverse,
               utils, 
               haven)

```

Polite scraping 
```{r}
bow("https://www.nzherald.co.nz/",
  user_agent = "Sofia Lai - https://github.com/sofialai",
  delay = 5, force = FALSE, verbose = FALSE)
```


Scraper 
```{r}
parsed_nz_herald <- read_html("https://www.nzherald.co.nz/") 

headlines_nz_herald <- parsed_nz_herald%>% 
  rvest::html_nodes('body') %>%
  xml2::xml_find_all("//a[contains(@class, 'story-card__heading__link')]") %>%
  html_text %>% 
  unique() %>% 
  tolower() %>% 
  as.data.frame()

write.table(headlines_nz_herald, "./nz_herald_headlines.csv", append = TRUE, row.names = FALSE)

dat_nz_herald <- read_csv("./nz_herald_headlines.csv") %>% 
  unique() 

write.table(dat_nz_herald, "./nz_herald_headlines.csv", row.names = FALSE)
```