# English country list

library(tidyverse)

eng_countries <- c("china","chinese*", "india*", "indian", "united states", "united states", "america*",
                   "indonesia*", "pakistan*", "brazil*", "nigeria",  "nigerian", "bangladesh*", 
                   "russia*", "russian", 
                   "mexic*",  "japan*", "tokyo", "ethiopia*", "philippine*", "filipino*", 
                   "egypt*", "vietnam*", "congo*", "iran*", "turkey*", "turkish", "german*", 
                   "france", "french*", "united kingdom", "uk", "england", "britain", "britains", 
                   "scotland", "scotland", "scottish", "scottish", "wales", "welsh",
                   "thailand", "thailands", "thai", "south africa*", "tanzan*", "italy", "italys",  
                   "italian", "italians", "myanmar*", 
                   "burmese", "south korea", "korea*", "colombia*", "kenya*", "spain*", "spanish*", 
                   "argentin*", "algeria*", "sudan*", "uganda*", "ukrain*", "iraq", "iraqi", 
                   "canad*", "poland*", "polish*", "morocc*", "uzbekist*", "saudi arabia*", 
                   "arabia*", "peru", "peruvian", "afghanistan", "afghanistani", "afghan", "afghani", 
                   "malaysia", "malaysian", "angola*", 
                   "mozambi*", 
                   "ghana", "ghanaian", "yemen*", "nepal*", "venezuel*", "ivory coast*", "divoire*",  
                   "madagascar*", "malagas*", "australia", "australian", "north korea*", "cameroon*", 
                   "niger", "nigers", "taiwa*", "sri lanka*", "lanka*", "burkin*", 
                   "mali", "malian", "chile", "chilian", "romania*", "kazakhst*", "malawi*", "malawian", 
                   "zambia*", "syria*", "ecuador*", "netherlan*", "dutch*", "seneg*", 
                   "guatema*", "chad", "chadian", "somali*", "zimbab*", "cambodi*", "south sudan*", 
                   "rwand*", "guinea*", "burund*", "benin*", "bolivi*", "tunisia*", 
                   "haiti*", "belgi*", "cuba*", "jordan*", "greece*", "greek*", "czech*", 
                   "dominican republ*", "dominic*", "sweden", "swedish", "portug*", 
                   "azerbaij*", "hungar*", "tajikist*", "united arab emirates*", "emirat*", 
                   "hondur*", "israel*", "belaru*", "papua new guinea*", "papua*", 
                   "austria", "switzer*", "swiss*", "sierra leone*", "leon*", "togo", "togolese", 
                   "hong kong*", "kong*", "paragu*", "laos", "laotian", "libya", "libyan", "bulgar*", 
                   "serbia", "serb", "el salvador", "salvador*", "leban*", "kyrgyzst*", 
                   "nicarag*", "turkmenist*", "denmark*", "danish*", "congolese", 
                   "central african republic*", "central african*", "finland", "finlands", "finn", "finnish", 
                   "slovak*", "singapor*", "norway", "norwegian", "palestin*", "costa rica*", "new zealand*", 
                   "ireland*", "irish*", "liberi*", "oman", "omani", "kuwait*", "panama*", 
                   "mauritan*", "croati*", "georgia*", "eritr*", "urugu*", 
                   "mongoli*", "bosnia and herzegovina*", "bosni*", "puerto rico*", 
                   "armeni*", "albani*", "lithuani*", "jamaic*", "moldov*", "namibia*", 
                   "gambia*", "botswan*", "motswana", "qatar*", "gabon*", "lesotho*", "mosotho", 
                   "basotho", "sloveni*", "north macedonia*", "macedoni*", "latvi*", 
                   "kosov*", "guinea bissau*", "bissau-guinean*", "equatorial guinea", 
                   "equatoguinean*", "bahrai*", "trinidad and tobago*", "trinidad*", "tobagoni*",
                   "estoni*", "east timor*", "timorian", "mauritius", "eswatini*", "emaswat*", "liswat*",
                   "djibout*", "fiji*", "cypr*", "comoros*", "bhuta*", "guyan*", "solomon islands*", 
                   "macau*", "macanese*", "macao", "luxembourg*", "montenegr*", "western sahara*", "surinam*", 
                   "cape verd*", "cabo verd*", "malta*", "maltese*", "transnistr*", "brunei*", "belize", "belizean",
                   "baham*", "maldiv*", "iceland*", "northern cyprus*", "vanuat*", "barbad*", 
                   "french polynesi*", "new caledoni*", "abkhaz*", "são tomé", "samoa*", "saint lucia*", 
                   "guam", "curaça*", "artsakh*", "kiribat*", "grenad*", "aruba", "saint vincent and the grenadines*",
                   "saint vincentian*", "jersey*", "micronesi*", "u s virgin islands*", "tonga*", "antigua and barbuda*", 
                   "antiguan", "barbudan", "seychell*", "isle of man", "manx", "andorr*", 
                   "dominica*", "cayman*", "bermud*", "guerns*", "american samoa*", "northern mariana islands*", 
                   "greenlan*", "marshall island*", "saint kitts and nevis*", "kittian*", "nevisian*",
                   "ossetia*", "faroe*", "turks and caicos islands*", "maarten*",  "liechtenstein*", 
                   "monac*", "saint martin*",  "gibralta*", "san marino*", "sammarinese*", 
                   "åland", "british virgin islands*", "palau*", "cook islands*", 
                   "anguill*", "nauru*", "wallis and futuna*", "wallisian", "futunan",  
                   "tuvalu*", "saint barth*", "saint helen*", "heleni*", "ascension*", "tristan da cunha*", 
                   "tristia*",  "saint pierre and miquelon*", "saint-pierrais*", "montserrat*", 
                   "falkland islands*", "christmas island*", "norfolk island*", "niue*", 
                   "tokelau*", "vatican*", "cocos keeling islands*", "pitcairn islands*",
                   "asia", "asian", "europe*", "africa", "african",
                   "south georgia and the islands", "british indian ocean territory", "somaliland", 
                   "são tomé and principe", "french southern and antarctic lands", "indian ocean territories", 
                   "heard island and mcdonald islands", "ashmore and cartier islands", "siachen glacier", "antarctica",
                   "washington", "new york", "berlin", "paris", "london", "brussels", "rome", "dublin", 
                   "belfast", "canberra", 
                   "sydney", "wellington", "auckland")



ADMIN2 <- c("China","China", "India", "India", "United States of America", "United States of America", 
            "United States of America",
            "Indonesia", "Pakistan", "Brazil", "Nigeria",  "Nigeria", "Bangladesh", "Russia", "Russia", 
            "Mexico",  "Japan", "Japan", "Ethiopia", "Philippines", "Philipines", 
            "Egypt", "Vietnam", "Democratic Republic of the Congo", "Iran", "Turkey", "Turkey", 
            "Germany", "France", "France*", "United Kingdom", "United Kingdom", "United Kingdom", 
            "United Kingdom", "United Kingdom", "United Kingdom", "United Kingdom", "United Kingdom", 
            "United Kingdom", "United Kingdom", "United Kingdom",
            "Thailand", "Thailand", "Thailand", "South Africa", "United Republic of Tanzania", "Italy", "Italy",  
            "Italy", "Italy", "Myanmar", 
            "Myanmar", "South Korea", "South Korea", "Colombia", "Kenya", "Spain", "Spain", 
            "Argentina", "Algeria", "Sudan", "Uganda", "Ukraine", "Iraq", "Iraq", 
            "Canada", "Poland", "Poland", "Morocco", "Uzbekistan", "Saudi Arabia", 
            "Saudi Arabia", "Peru", "Peru", "Afghanistan", "Afghanistan", "Afghanstan", "Afghanstan", 
            "Malaysia", "Malaysia", "Angola", "Mozambique", 
            "Ghana", "Ghana", "Yemen", "Nepal", "Venezuela", "Ivory Coast", "Ivory Coast",  
            "Madagascar", "Madagascar", "Australia", "Australia", "North Korea", "Cameroon", 
            "Niger", "Niger", "Taiwan", "Sri Lanka", "Sri Lanka", "Burkina Faso", 
            "Mali", "Mali", "Chile", "Chile", "Romania", "Kazakhstan", "Malawi", "Malawi", 
            "Zambia", "Syria", "Ecuador", "Netherlands", "Netherlands", "Senegal", 
            "Guatemala", "Chad", "Chad", "Somalia", "Zimbabwe", "Cambodia", "South Sudan", 
            "Rwanda", "Guinea", "Burundi", "Benin", "Bolivia", "Tunisia", 
            "Haiti", "Belgium", "Cuba", "Jordan", "Greece", "Greece*", "Czechia", 
            "Dominican Republic", "Dominican Rpublic", "Sweden", "Sweden", "Portugal", 
            "Azerbaijan", "Hungary", "Tajikistan", "United Arab Emirates", "United Arab Emirates", 
            "Honduras", "Israel", "Belarus", "Papua New Guinea*", "Papua New Guinea", 
            "Austria", "Switzerland", "Switzerland", "Sierra Leone*", "Sierra Leone", 
            "Togo", "Togo", 
            "Hong Kong S.A.R.", "Hong Kong S.A.R.", "Paraguay", "Laos", "Loas", "Libya", "Libya", "Bulgaria", 
            "Republic of Serbia", "Republic of Serbia", "El Salvador", "El Salvador", "Lebanon", "Kyrgyzstan", 
            "Nicaragua", "Turkmenistan", "Denmark", "Danmark", "Republic of the Congo", 
            "Central African Republic", "Central African Republic", "Finland", "Finland", "Finland", 
            "Finland", 
            "Slovakia", "Singapore", "Norway", "Norway", "Palestine", "Costa Rica", "New Zealand", 
            "Ireland", "Ireland", "Liberia", "Oman", "Oman", "Kuwait", "Panama", 
            "Mauritania", "Croatia", "Georgia", "Eritrea", "Uruguay", 
            "Mongolia", "Bosnia and Herzegovina", "Bosnia and Herzegovina", "Puerto Rico", 
            "Armenia", "Albania", "Lithuania", "Jamaica", "Moldova", "Namibia", 
            "Gambia", "Botswana", "Botswana", "Qatar", "Gabon", "Lesotho", "Lesotho", 
            "Lesotho", "Slovenia", "North Macedonia", "North Macedonia", "Latvia", 
            "Kosovo", "Guinea-Bissau", "Guinea-Bissau", "Equatorial Guinea", 
            "Equatorial Guinea", "Bahrain", "Trinidad and Tobago", "Trinidad and Tabago", 
            "Trinidad and Tobago",
            "Estonia", "East Timor", "East Timor", "Mauritius", "eSwatini", " eSwatini ", " eSwatini ",
            "Djibouti", "Fiji", "Cyprus", "Comoros", "Bhutan", "Guyana", "Solomon Islands", 
            "Macao S.A.R", "Macau S.A.R", "Macau S.A.R", "Luxembourg", "Montenegro", "Western Sahara", "Suriname", 
            "Cape Verde", "Cabo Verde", "Malta", "Malta", "Transnistria", "Brunei", "Belize", "Belize",
            "The Bahamas", "Maldives", "Iceland", "Northern Cyprus", "Vanuatu", "Barbados", 
            "French Polynesia", "New Caledonia", "Abkhazia", "São Tomé", "Samoa", "Saint Lucia", 
            "Guam", "Curaçao", "Artsakh", "Kiribati", "Grenada", "Aruba", 
            "Saint Vincent and the Grenadines",
            "Saint Vincent and the Grenadines", "Jersey", "Federated States of Micronesia", "United States Virgin Islands", 
            "Tonga", "Antigua and Barbuda", 
            "Antigua and Barbuda", "Antigua and Barbuda", "Seychelles", "Isle of Man", 
            "Isle of Man", "Andorra", 
            "Dominica", "Cayman Islands", "Bermuda", "Guernsey", "American Samoa", "Northern Mariana Islands", 
            "Greenland", "Marshall Islands", "Saint Kitts and Nevis", "Saint Kitts and Nevis", 
            "Saint Kitts and Nevis",
            "Ossetia", "Faroe Islands", "Turks and Caicos Islands", "Sint Maarten",  "Liechtenstein", 
            "Monaco", "Saint Martin",  "Gibralta", "San Marino", "San Marino", 
            "Aland", "British Virgin Islands", "Palau", "Cook Islands", 
            "Anguilla", "Nauru", "Wallis and Futuna*", "Wallis and Futuna", "Wallis and Futuna",  
            "Tuvalu", "Saint Barthelemy", "Saint Helena", "Saint Helena", "Ascension", 
            "Tristan da Cunha", 
            "Tristan da Cunha",  "Saint Pierre and Miquelon", "Saint Pierre and Miquelon", "Montserrat", 
            "Falkland Islands", "Christmas Island", "Norfolk Island", "Niue", 
            "Tokelau", "Vatican", "Cocos Keeling Islands", "Pitcairn Islands",
            "Asia", "Asia", "Europe", "Africa", "Africa", 
            "South Georgia and the Islands", "British Indian Ocean Territory", "Somaliland", "São Tomé and Principe", 
            "French Southern and Antarctic Lands", "Indian Ocean Territories", "Heard Island and McDonald Islands", 
            "Ashmore and Cartier Islands", "Siachen Glacier", "Antarctica", "United States of America", "United States of America", "Germany", "France", "United Kingdom",
            "Belgium", "Italy", "Ireland", "United Kingdom", "Australia", "Australia", "New Zealand", "New Zealand")



eng_countries_df <- data_frame(eng_countries)
admin <- data_frame(ADMIN2)

eng_countries_full <- cbind(admin, eng_countries_df)

oman_words <- c("woman", "romance", "homan", "romane", "roman", "coman", "romane", "romantisme", "romantique", 
                "fromanger", "romancière", "lisztomanias", "pétomane", "romancier", "romantik", "romanik",
                "romanusbad")


