# French country list

library(tidyverse)

fr_countries <- c("chine", "chinois*", "inde*", "inde", "états-unis", "etats-unis", "amérique*",
                  "indonésie*", "pakistan*", "brésil*", "nigeria", "nigérian*", "bangladesh*", 
                  "russie*", "russie",
                  "mexique*", "japon*", "tokyo", "ethiopie*", "philippine*", "philippin*",
                  "egypt*", "vietnam*", "congo*", "iran*", "turquie*", "turc", "allemand*",
                  "france", "français*", "royaume-uni", "uk", "england", "bretagne", "bretagnes",
                  "ecosse", "écosse", "ecossais*", "écossais*", "pays de galles", "gallois*",
                  "thaïlande", "thaïlande", "thaï", "afrique du sud*", "tanzan*", "italie", "italie",
                  "italien", "italiens", "myanmar*",
                  "birmie", "corée du sud", "coréen*", "colombie*", "kenya*", "espagne*", "espagnol*",
                  "argentin*", "algérie*", "soudan*", "ouganda*", "ukrain*", "irak", "irakien",
                  "canad*", "pologne*", "polonais*", "maroc*", "ouzbek*", "arabie saoudite*",
                  "arabie*", "perou", "péruvien", "afghanistan", "afghanistani", "afghan", "afghani",
                  "malaisie", "malaisienne", "angola*",
                  "mozambi*",
                  "ghana", "ghanaian", "yémen*", "népal*", "venezuel*", "côte d'ivoire*", "divoire*",
                  "madagascar*", "malagas*", "australie", "australien", "corée du nord*", "cameroun*",
                  "niger", "nigers", "taiwa*", "sri lanka*", "lanka*", "burkin*",
                  "mali", "malien", "chili", "chilien", "roumanie*", "kazakhst*", "malawi*", "malawien",
                  "zambie*", "syrie*", "équateur*", "néerlandais*", "néerlandais*", "sénég*",
                  "guatema*", "tchad", "tchadienne", "somali*", "zimbab*", "cambodi*", "soudan du sud*",
                  "rwand*", "guinée*", "burund*", "benin*", "bolivi*", "tunisie*",
                  "haiti*", "belgi*", "cuba*", "jordan*", "greece*", "greek*", "tcheque*",
                  "république dominicaine*", "dominic*", "suède*", "suède*", "portug*",
                  "azerbaij*", "hungar*", "tadjikist*", "émirats arabes unis*", "émirat*",
                  "hondur*", "israel*", "belaru*", "papouasie-nouvelle-guinée*", "papouasie*",
                  "autriche", "suisse*", "suisse*", "sierra leone*", "leon*", "togo", "togolais",
                  "hong kong*", "kong*", "paragu*", "laos", "laotien", "libya", "libyan", "bulgar*",
                  "serbie", "serbe", "el salvador", "salvador*", "liban*", "kirghiz*",
                  "nicarag*", "turkméniste*", "danemark*", "danois*", "congolais",
                  "république centrafricaine*", "centre-africain*", "finlande", "finlands", "finlandais", "finlandais",
                  "slovaque*", "singapour*", "norvège", "norvégien", "palestin*", "costa rica*", "nouvelle-zélande*",
                  "irlande*", "irlandais*", "liberi*", "oman", "omani", "koweït*", "panama*",
                  "mauritanien*", "croate*", "géorgie*", "eritr*", "urugu*",
                  "mongoli*", "bosnie-herzégovine*", "bosni*", "porto rico*",
                  "armeni*", "albani*", "lithuani*", "jamaic*", "moldov*", "namibie*",
                  "gambie*", "botswan*", "motswana", "qatar*", "gabon*", "lesotho*", "mosotho",
                  "basotho", "sloveni*", "macédoine du nord*", "macedoni*", "latvi*",
                  "kosov*", "guinée bissau*", "bissau-guinéen*", "guinée équatoriale",
                  "équatoguinéen*", "bahrai*", "trinidad et tobago*", "trinidad*", "tobagoni*",
                  "estoni*", "timor oriental*", "timorian", "maurice", "eswatini*", "emaswat*", "liswat*",
                  "djibout*", "fidji*", "cypr*", "comores*", "bhuta*", "guyan*", "îles salomon*",
                  "macao*", "macanese*", "macao", "luxembourg*", "montenegr*", "western sahara*", "surinam*",
                  "cap-vert*", "cabo verd*", "malte*", "maltais*", "transnistr*", "brunei*", "belize", "belizean",
                  "baham*", "maldiv*", "Islande*", "nord de chypre*", "vanuat*", "barbad*",
                  "french polynesi*", "new caledoni*", "abkhaz*", "são tomé", "samoa*", "saint lucia*",
                  "guam", "curaça*", "artsakh*", "kiribat*", "grenad*", "aruba", "saint vincent et les grenadines*",
                  "saint vincentian*", "jersey*", "micronesi*", "u s virgin Islands*", "tonga*", "antigua-et-barbuda*",
                  "antiguan", "barbudan", "seychell*", "isle of man", "manx", "andorr*",
                  "dominica*", "cayman*", "bermud*", "guerns*", "american samoa*", "northern mariana Islands*",
                  "greenlan*", "île marshall*", "saint kitts et nevis*", "kittian*", "nevisian*",
                  "ossetia*", "faroe*", "turks and caicos Islands*", "maarten*", "liechtenstein*",
                  "monac*", "saint martin*", "gibralta*", "san marino*", "sammarinese*",
                  "åland*", "îles vierges britanniques*", "palau*", "îles Cook*",
                  "anguill*", "nauru*", "wallis et futuna*", "wallisian", "futunan",
                  "tuvalu*", "saint barth*", "saint helen*", "heleni*", "ascension*", "tristan da cunha*",
                  "tristia*", "saint pierre et miquelon*", "saint-pierrais*", "montserrat*",
                  "îles Falkland*", "île de Noël*", "île de Norfolk*", "niue*",
                  "tokelau*", "vatican*", "cocos keeling Islands*", "pitcairn Islands*",
                  "asia", "asiatique", "europe*", "afrique", "africain",
                  "géorgie du sud et les îles", "territoire britannique de l'océan indien", "somaliland",
                  "são tomé et principe", "terres australes et antarctiques françaises", "territoires océan indien",
                  "île Heard et îles mcdonald", "îles ashmore et cartier", "glacier siachen", "antarctique",
                  "washington", "new york", "berlin", "paris", "londres", "bruxelles", "rome", "dublin", "belfast",
                  "canberra", "sydney", "wellington", "auckland")

fr_countries_df <- data_frame(fr_countries)

fr_countries_full <- cbind(admin, fr_countries_df) #admin is from eng_country_list script
