

library(tidyverse)

ger_countries <- c("china","chinesisch*", "indien", "indisch*", "vereinigte staaten", "usa", "amerika*",
                   "indonesien*", "pakistan*", "brasilien*", "nigeria", "nigerianisch*", 
                   "bangladesch*", "russland*", "russisch*",
                   "mexik*", "japan*", "tokio", "äthiopien*", "philippinen*", "philippinisch*",
                   "ägypt*", "vietnam*", "kongo*", "iran*", "türkei*", "türkisch", "deutsch*",
                   "frankreich", "französisch*", "großbritannien", "großbritannien", "england", 
                   "großbritannien", "großbritannien",
                   "schottland", "schottland", "schottisch", "schottisch", "wales", "walisisch*",
                   "thailand", "thailand", "thailädisch*", "südafrika*", "tanzan*", "italien", "italien",
                   "italiener", "italiener", "myanmar*",
                   "birmanisch*", "südkorea", "korea*", "kolumbien*", "kenia*", "spanien*", "spanisch*",
                   "argentinien*", "algerien*", "sudan*", "uganda*", "ukrain*", "irak", "irakisch",
                   "kanada*", "polen*", "polnisch*", "marokk*", "usbekist*", "saudi-arabien*",
                   "arabien*", "peru", "peruanisch", "afghanistan", "afghanistan", "afghanisch", "afghani",
                   "malaysia", "malaysisch", "angola*",
                   "mosambik*",
                   "ghana", "ghanaisch", "jemen*", "nepal*", "venezola*", "elfenbeinküste*", "divoire*",
                   "madagaskar*", "madagas*", "australien", "australier", "nordkorea*", "kamerun*",
                   "niger", "nigers", "taiwa*", "sri lanka*", "lanka*", "burkin*",
                   "mali", "malisch*", "chile", "chilian", "rumänien*", "kasachst*", "malawi*", "malawisch",
                   "sambia*", "syrien*", "ecuador*", "niederlande*", "niederländisch*", "seneg*",
                   "guatema*", "tschad", "tschadisch", "somali*", "zimbab*", "cambodi*", "südsudan*",
                   "rwand*", "guinea*", "burund*", "benin*", "bolivi*", "tunesien*",
                   "haiti*", "belgien*", "kuba*", "jordanien*", "griechenland*", "griechisch*", "tschechisch*",
                   "dominikanische republik", "dominikanish*", "schweden*", "schwedisch*", "portug*",
                   "aserbaidsch*", "hungar*", "tadschikist*", "vereinigte arabische emirate*", "emirat*",
                   "hondur*", "israel*", "belaru*", "papua-neuguinea*", "papua*",
                   "österreich", "schweiz*", "schweizerisch*", "sierra leone*", "leon*", "togo", "togoisch*",
                   "hong kong*", "kong*", "paragu*", "laos", "laotisch*", "libya", "libyan", "bulgar*",
                   "serbien", "serbisch", "el salvador", "salvadorian*", "liban*", "kyrgyzst*",
                   "nikarag*", "turkmenist*", "dänemark*", "dänisch*", "kongolesisch",
                   "zentralafrikanische republik*", "zentralafrikanisches*", "finnland", "finnland", "finn", "finnisch",
                   "slowakisch*", "singapor*", "norwegen", "norwegisch", "palästina*", "costa rica*", "neuseeland*",
                   "irland*", "irisch*", "liberi*", "oman", "omanisch", "kuwait*", "panama*",
                   "mauritan*", "kroati*", "georgia*", "eritr*", "urugu*",
                   "mongoli*", "bosnien und herzegowina*", "bosni*", "puerto rico",
                   "armeni*", "albani*", "lithuani*", "jamaic*", "moldov*", "namibia*",
                   "gambia*", "botswan*", "motswana", "qatar*", "gabon*", "lesotho*", "mosotho",
                   "basotho", "sloveni*", "nordmazedonien*", "macedoni*", "latvi*",
                   "kosov*", "guinea bissau*", "bissau-guinean*", "äquatorialguinea",
                   "äquatoguineisch*", "bahrai*", "trinidad und tobago*", "trinidad*", "tobagoni*",
                   "estoni*", "osttimor*", "timorianer", "mauritius", "eswatini*", "emaswat*", "liswat*",
                   "djibout*", "fiji*", "cypr*", "comoren*", "bhuta*", "guyan*", "salomonen*",
                   "macau*", "macanese*", "macau", "luxemburg*", "montenegr*", "westsahara*", "surinam*",
                   "kap verd*", "kapverdisch*", "malta*", "malteser*", "transnistr*", "brunei*", "belize", "belizean",
                   "baham*", "maldiv*", "island*", "nordzypern*", "vanuat*", "barbad*",
                   "französisch-polynesien*", "neukaladon*", "abchasen*", "são tomé", "samoa*", "saint lucia*",
                   "guam", "curaça*", "artsakh*", "kiribat*", "grenad*", "aruba", "saint vincent und die grenadinen*",
                   "saint vincentian*", "jersey*", "micronesi*", "amerikanische jungferninseln", "tonga*", 
                   "antigua und barbuda*",
                   "antiguan", "barbudan", "seychell*", "isle of man", "manx", "andorr*",
                   "dominica*", "cayman*", "bermud*", "guerns*", "amerikanisch-samoa*", "nördliche marianen*",
                   "grönland*", "marshall island*", "sint kitts and nevis*", "kittian*", "nevisian*",
                   "ossetia*", "faröer*", "türken- und caicosinseln*", "maarten*", "liechtenstein*",
                   "monac*", "sint martin*", "gibralta*", "san marino*", "sammarinese*",
                   "åland", "britische jungferninseln*", "palau*", "cook Islands*", "anguill*", "nauru*", 
                   "wallis und futuna*", "wallisian", "futunan",
                   "tuvalu*", "saint barth*", "saint helen*", "heleni*", "ascension*", "tristan da cunha*",
                   "tristia*", "saint pierre und miquelon*", "saint-pierrais*", "montserrat*",
                   "falklandinseln*", "weihnachtsinsel*", "norfolkinsel*", "niue*",
                   "tokelau*", "vatican*", "cocos kieling islands*", "pitcairn islands*",
                   "asien", "asiatisch", "europa*", "afrika", "afrikanisch",
                   "südgeorgien und die inseln", "britisches territorium im indischen ozean", "somaliland",
                   "são tomé und principe", "französische südliche und antarktische länder", 
                   "territorien des indischen ozeans",
                   "heard island und mcdonald islands", "ashmore und cartier islands", "siachen glacier", "antarktis",
                   "washington", "new york", "berlin", "paris", "london", "brüssel", "rom", "dublin",
                   "belfast", "canberra", "sydney", "wellington", "auckland")

ger_countries_df <- data_frame(ger_countries)

ger_countries_full <- cbind(admin, ger_countries_df) #admin is from eng_country_list script
